services:
  - type: web
    name: alpaca-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn alpacabackend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: alpacabackend.settings